name: Page Workflow

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Build
        run: |
          npm install yarn
          yarn
          CI=false yarn run build
        env:
          REACT_APP_GITHUB_TOKEN: ${{secrets.REACT_APP_GITHUB_TOKEN}}
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{secrets.REACT_APP_GITHUB_TOKEN}}
          BRANCH: gh-pages
          FOLDER: build